# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v --junitxml=test-reports/report.xml --html=test-reports/report.html
      env:
        GH_TOKEN: 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
        HOST: http://tutorialsninja.com/demo/
        NETWORK: good
        SELENIUM_DRIVER_KIND: remote
        WINDOW_RESOLUTION: max
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: test-reports
    - name: Parsing_results
      run: |
        pytest > pytest_output.txt |
        cat pytest_output.txt | python parse_tests_results.py

    services:
      headless:
        image: browserless/chrome:latest
        ports:
          - 3000:3000
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.REPOSITORY_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          avatar-url: 'https://cdn.pixabay.com/photo/2022/01/30/13/33/github-6980894_1280.png'
          title: 'Tests: {{STATUS}}'
          description: '${{ steps.Parsing_results.output }}'
          include-details: 'true'
          color-success: '#00BD39'
          color-failure: '#FF0000'
          color-cancelled: '#FF7400'